title: Tsukino Blog
author: Kurai Tsukino
email: sandym3000@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Un blog escrito por Kurai Tsukino sobre temas de programación

# social links
twitter_username: Kurai_Tsukino
github_username:  KuraiTsukino

theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
